title: AI Integration in Construction Education
description: Methods, Resources, and Implementation Strategies
theme: jekyll-theme-cayman
show_downloads: false

# Custom theme options
github:
  is_project_page: true
  repository_url: https://github.com/morehosseini/AI-Integration-in-Construction-Education
